### ISSUE TITLE
tips to be able to add rtl?

### ISSUE THREAD

**Issue by markus-azer** [uilibrary/Bazar-Pro-Issues-and-Feature-request#2]
is there any tips to add rtl?

Thanks :)

**Comment by mh-rafi** [comment]
You can use this package to add rtl feature https://www.npmjs.com/package/stylis-plugin-rtl

You also need to update html and Material theme
file public/index.html
`<body dir="rtl"></body>`

File src/theme/theme.ts#L34
`const theme = createTheme({
  direction: 'rtl',
});`

Please check https://next.material-ui.com/guides/right-to-left/
