### ISSUE TITLE
about @mui/material

### ISSUE THREAD

**Issue by keahke** [uilibrary/Bazar-Pro-Issues-and-Feature-request#3]
hi, I've bought this theme, everything runs great for now.

but recently Material UI team has released their 5.0.0-RC on [@mui/material](https://www.npmjs.com/package/@mui/material) instead of [@material-ui/core](https://www.npmjs.com/package/@material-ui/core), will the theme update to use @mui/material for more support? thank you!

**Comment by mh-rafi** [comment]
Hi, We'll update the package names in imports soon.

**Comment by taksatou** [comment]
Any updates? We're also waiting for the update. Thank you!

**Comment by piyushpriyadarshi** [comment]
h

> hi, I've bought this theme, everything runs great for now.
> 
> but recently Material UI team has released their 5.0.0-RC on [@mui/material](https://www.npmjs.com/package/@mui/material) instead of [@material-ui/core](https://www.npmjs.com/package/@material-ui/core), will the theme update to use @mui/material for more support? thank you!

hi, what we will get if i purchase this theme, will i get the complete source code and figma resources ?

**Comment by mh-rafi** [comment]
@piyushpriyadarshi  You will get complete source. If will get figma with Standard plus and extended license.

**Comment by mh-rafi** [comment]
> Any updates? We're also waiting for the update. Thank you!

Updates are coming are within few days. we're working on this.

**Comment by mh-rafi** [comment]
Updates are released on [MUI store](https://material-ui.com/store/items/bazar-pro-react-ecommerce-template/)
