### ISSUE TITLE
heap size npm run build

### ISSUE THREAD

**Issue by shahramRezvani** [uilibrary/Bazar-Pro-Issues-and-Feature-request#4]
<--- Last few GCs --->

[49291:0x1026a0000]   156688 ms: Mark-sweep 2016.8 (2066.5) -> 2003.0 (2068.5) MB, 1209.2 / 0.0 ms  (average mu = 0.206, current mu = 0.131) allocation failure scavenge might not succeed
[49291:0x1026a0000]   158203 ms: Mark-sweep 2019.2 (2068.5) -> 2001.6 (2068.5) MB, 1149.5 / 0.1 ms  (average mu = 0.224, current mu = 0.241) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x100ea9f02]
Security context: 0x20b1e1f1a2f1 <JSObject>
    1: /* anonymous */ [0x20b10a0f88a1] [/Users/macbookpro/Desktop/bazar-react 2/node_modules/next/dist/compiled/babel/bundle.js:~2194] [pc=0x239d6b948ceb](this=0x20b1db8db119 <JSFunction traverse (sfi = 0x20b1546f3ac9)>,0x20b107b13ac9 <Object map = 0x20b196b02989>,0x20b1db8e9f29 <Object map = 0x20b19ae52259>,0x20b107b26691 <Scope map = 0x20b196b24039>,0x20b107...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20210922.115938.49291.0.001.json
Node.js report completed
 1: 0x100075bd5 node::Abort() [/usr/local/bin/node]
 2: 0x100076316 node::errors::TryCatchScope::~TryCatchScope() [/usr/local/bin/node]
 3: 0x1001697d7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10016976c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1005480d5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x1005491c3 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 7: 0x100546bc3 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10054487f v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x10054f365 v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x10054f3df v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x10051e10f v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
12: 0x1007cecf4 v8::internal::Runtime_AllocateInNewSpace(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x100ea9f02 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
zsh: abort

**Comment by mh-rafi** [comment]
On my side "npm run build" is working fine. 
Can you add this NODE_OPTIONS=--max-old-space-size=4096 to build script in package.json?
`"build": "next build NODE_OPTIONS=--max-old-space-size=4096"`

Seems like lots of people also facing this issue https://github.com/vercel/next.js/issues/7929
