### ISSUE TITLE
Error to use axois/typescript to fetch data from web api

### ISSUE THREAD

**Issue by rattanak** [uilibrary/Bazar-Pro-Issues-and-Feature-request#5]
It's error to use axios in typescript to fetch data. Could you pls help to guid some tips to fetch products from web api in your product-database.ts file?

I'm new with react, typescript and next js.

**Comment by mh-rafi** [comment]
Hi, we've integrated rest api to grocery store. Can you check that? 

We've also integrating to all pages. We'll release that update soon.
