### ISSUE TITLE
while updating any reducer state other reducer states being undefined

### ISSUE THREAD

**Issue by ozvaris** [uilibrary/Bazar-Pro-Issues-and-Feature-request#6]
For examplei if you add any item the basket layout state being undefined.

I think found the issue. To fix that problem, return state  from the default case of reducers.  After that, if action could't be found in combinereducer for loop it return current reducer state.

![image](https://user-images.githubusercontent.com/10708141/145354318-20c0c62c-def8-4389-abeb-2dcf496fc3c0.png)

**Comment by mh-rafi** [comment]
@ozvaris Thank you so much! We're going to fix this in our main repo.
